[package]
name = "scribedown"
author = "Alexis Dumas"
version = "0.0.1"
edition = "2021"

[dependencies]
gtk          = "0.15.3"
once_cell    = "1.9.0"
regex        = "1.5.4"
lazy_static  = "1.4.0"
comrak       = "0.12"